/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SearchRouteImport } from './routes/search'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollegesSlugRouteImport } from './routes/colleges.$slug'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedCollegeAdminRouteImport } from './routes/_authenticated/college-admin'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedPremiumIndexRouteImport } from './routes/_authenticated/premium/index'
import { Route as AuthenticatedPremiumTopicsRouteImport } from './routes/_authenticated/premium/topics'
import { Route as AuthenticatedPremiumReviewsRouteImport } from './routes/_authenticated/premium/reviews'
import { Route as AuthenticatedPremiumReportRouteImport } from './routes/_authenticated/premium/report'
import { Route as AuthenticatedPremiumProfileRouteImport } from './routes/_authenticated/premium/profile'
import { Route as AuthenticatedPremiumAnalyticsRouteImport } from './routes/_authenticated/premium/analytics'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesSlugRoute = CollegesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollegesRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollegeAdminRoute =
  AuthenticatedCollegeAdminRouteImport.update({
    id: '/college-admin',
    path: '/college-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPremiumIndexRoute =
  AuthenticatedPremiumIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumTopicsRoute =
  AuthenticatedPremiumTopicsRouteImport.update({
    id: '/topics',
    path: '/topics',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumReviewsRoute =
  AuthenticatedPremiumReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumReportRoute =
  AuthenticatedPremiumReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumProfileRoute =
  AuthenticatedPremiumProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumAnalyticsRoute =
  AuthenticatedPremiumAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/college-admin': typeof AuthenticatedCollegeAdminRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/premium': typeof AuthenticatedPremiumRouteWithChildren
  '/resources': typeof AuthenticatedResourcesRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/premium/analytics': typeof AuthenticatedPremiumAnalyticsRoute
  '/premium/profile': typeof AuthenticatedPremiumProfileRoute
  '/premium/report': typeof AuthenticatedPremiumReportRoute
  '/premium/reviews': typeof AuthenticatedPremiumReviewsRoute
  '/premium/topics': typeof AuthenticatedPremiumTopicsRoute
  '/premium/': typeof AuthenticatedPremiumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/college-admin': typeof AuthenticatedCollegeAdminRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/premium/analytics': typeof AuthenticatedPremiumAnalyticsRoute
  '/premium/profile': typeof AuthenticatedPremiumProfileRoute
  '/premium/report': typeof AuthenticatedPremiumReportRoute
  '/premium/reviews': typeof AuthenticatedPremiumReviewsRoute
  '/premium/topics': typeof AuthenticatedPremiumTopicsRoute
  '/premium': typeof AuthenticatedPremiumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/college-admin': typeof AuthenticatedCollegeAdminRoute
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRouteWithChildren
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/colleges/$slug': typeof CollegesSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/premium/analytics': typeof AuthenticatedPremiumAnalyticsRoute
  '/_authenticated/premium/profile': typeof AuthenticatedPremiumProfileRoute
  '/_authenticated/premium/report': typeof AuthenticatedPremiumReportRoute
  '/_authenticated/premium/reviews': typeof AuthenticatedPremiumReviewsRoute
  '/_authenticated/premium/topics': typeof AuthenticatedPremiumTopicsRoute
  '/_authenticated/premium/': typeof AuthenticatedPremiumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/colleges'
    | '/mcp'
    | '/search'
    | '/submit'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/college-admin'
    | '/compare'
    | '/dashboard'
    | '/premium'
    | '/resources'
    | '/saved'
    | '/colleges/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/premium/analytics'
    | '/premium/profile'
    | '/premium/report'
    | '/premium/reviews'
    | '/premium/topics'
    | '/premium/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/colleges'
    | '/mcp'
    | '/search'
    | '/submit'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/college-admin'
    | '/compare'
    | '/dashboard'
    | '/resources'
    | '/saved'
    | '/colleges/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/premium/analytics'
    | '/premium/profile'
    | '/premium/report'
    | '/premium/reviews'
    | '/premium/topics'
    | '/premium'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analytics'
    | '/auth'
    | '/colleges'
    | '/mcp'
    | '/search'
    | '/submit'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/college-admin'
    | '/_authenticated/compare'
    | '/_authenticated/dashboard'
    | '/_authenticated/premium'
    | '/_authenticated/resources'
    | '/_authenticated/saved'
    | '/colleges/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/premium/analytics'
    | '/_authenticated/premium/profile'
    | '/_authenticated/premium/report'
    | '/_authenticated/premium/reviews'
    | '/_authenticated/premium/topics'
    | '/_authenticated/premium/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CollegesRoute: typeof CollegesRouteWithChildren
  McpRoute: typeof McpRoute
  SearchRoute: typeof SearchRoute
  SubmitRoute: typeof SubmitRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/$slug': {
      id: '/colleges/$slug'
      path: '/$slug'
      fullPath: '/colleges/$slug'
      preLoaderRoute: typeof CollegesSlugRouteImport
      parentRoute: typeof CollegesRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/college-admin': {
      id: '/_authenticated/college-admin'
      path: '/college-admin'
      fullPath: '/college-admin'
      preLoaderRoute: typeof AuthenticatedCollegeAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/premium/': {
      id: '/_authenticated/premium/'
      path: '/'
      fullPath: '/premium/'
      preLoaderRoute: typeof AuthenticatedPremiumIndexRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/topics': {
      id: '/_authenticated/premium/topics'
      path: '/topics'
      fullPath: '/premium/topics'
      preLoaderRoute: typeof AuthenticatedPremiumTopicsRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/reviews': {
      id: '/_authenticated/premium/reviews'
      path: '/reviews'
      fullPath: '/premium/reviews'
      preLoaderRoute: typeof AuthenticatedPremiumReviewsRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/report': {
      id: '/_authenticated/premium/report'
      path: '/report'
      fullPath: '/premium/report'
      preLoaderRoute: typeof AuthenticatedPremiumReportRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/profile': {
      id: '/_authenticated/premium/profile'
      path: '/profile'
      fullPath: '/premium/profile'
      preLoaderRoute: typeof AuthenticatedPremiumProfileRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/analytics': {
      id: '/_authenticated/premium/analytics'
      path: '/analytics'
      fullPath: '/premium/analytics'
      preLoaderRoute: typeof AuthenticatedPremiumAnalyticsRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPremiumRouteChildren {
  AuthenticatedPremiumAnalyticsRoute: typeof AuthenticatedPremiumAnalyticsRoute
  AuthenticatedPremiumProfileRoute: typeof AuthenticatedPremiumProfileRoute
  AuthenticatedPremiumReportRoute: typeof AuthenticatedPremiumReportRoute
  AuthenticatedPremiumReviewsRoute: typeof AuthenticatedPremiumReviewsRoute
  AuthenticatedPremiumTopicsRoute: typeof AuthenticatedPremiumTopicsRoute
  AuthenticatedPremiumIndexRoute: typeof AuthenticatedPremiumIndexRoute
}

const AuthenticatedPremiumRouteChildren: AuthenticatedPremiumRouteChildren = {
  AuthenticatedPremiumAnalyticsRoute: AuthenticatedPremiumAnalyticsRoute,
  AuthenticatedPremiumProfileRoute: AuthenticatedPremiumProfileRoute,
  AuthenticatedPremiumReportRoute: AuthenticatedPremiumReportRoute,
  AuthenticatedPremiumReviewsRoute: AuthenticatedPremiumReviewsRoute,
  AuthenticatedPremiumTopicsRoute: AuthenticatedPremiumTopicsRoute,
  AuthenticatedPremiumIndexRoute: AuthenticatedPremiumIndexRoute,
}

const AuthenticatedPremiumRouteWithChildren =
  AuthenticatedPremiumRoute._addFileChildren(AuthenticatedPremiumRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCollegeAdminRoute: typeof AuthenticatedCollegeAdminRoute
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRouteWithChildren
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCollegeAdminRoute: AuthenticatedCollegeAdminRoute,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRouteWithChildren,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CollegesRouteChildren {
  CollegesSlugRoute: typeof CollegesSlugRoute
}

const CollegesRouteChildren: CollegesRouteChildren = {
  CollegesSlugRoute: CollegesSlugRoute,
}

const CollegesRouteWithChildren = CollegesRoute._addFileChildren(
  CollegesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CollegesRoute: CollegesRouteWithChildren,
  McpRoute: McpRoute,
  SearchRoute: SearchRoute,
  SubmitRoute: SubmitRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
